import express from "express";
import cors from "cors";
import OpenAI from "openai";
const app=express(); const port=process.env.PORT||10000;
app.use(cors()); app.use(express.json({limit:"1mb"}));
app.get("/",(_req,res)=>res.json({ok:true,service:"Amor backend"}));
app.get("/health",(_req,res)=>res.json({ok:true}));
app.post("/api/chat",async(req,res)=>{try{if(!process.env.OPENAI_API_KEY)return res.status(500).json({error:"OPENAI_API_KEY is not configured."});const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const messages=Array.isArray(req.body?.messages)?req.body.messages.slice(-12):[];const profile=req.body?.profile||{};const input=messages.filter(m=>m&&(m.role==="user"||m.role==="assistant")&&typeof m.content==="string").map(m=>({role:m.role,content:m.content.slice(0,4000)}));const instructions=`Tu es Amor, coach amoureux de l'application Nature Amoureuse. Slogan : « L'amour est compliqué. Mais il est fait pour toi. » Tu aides uniquement pour les situations amoureuses et relationnelles : attirance, flirt, messages, couple, rupture, reconquête, jalousie, conflits, confiance, limites, communication et décisions relationnelles. Ton style est rassurant, mature, intelligent, direct et concret. Comprends d'abord la situation, analyse les faits et les hypothèses, puis donne une orientation et une action concrète. Ne pose une question que si elle est vraiment nécessaire. Respecte toujours le consentement, les limites et la dignité. Ne recommande jamais manipulation, harcèlement, stalking, humiliation ou jeux de jalousie. Ne garantis jamais un résultat. Si la demande n'est pas relationnelle, indique brièvement que tu es spécialisé dans les situations amoureuses. Profil : âge=${profile.age??"non précisé"}, formulation=${profile.identity??"non précisée"}, préférences=${profile.orientation??"non précisées"}.`;const response=await client.responses.create({model:process.env.OPENAI_MODEL||"gpt-6-astra",instructions,input});res.json({reply:response.output_text||"Je suis là. Raconte-moi ce qui se passe."});}catch(error){console.error(error);res.status(500).json({error:"AI request failed.",detail:error?.message||"Unknown error"});}});
app.listen(port,"0.0.0.0",()=>console.log(`Amor backend listening on port ${port}`));
